import sqlite3

conn = sqlite3.connect("app.db")
dbCursor = conn.cursor()


tableStrs = ("""CREATE TABLE BRANCHES(BID CHAR(6) PRIMARY KEY,
BNAME VARCHAR(64) UNIQUE NOT NULL,
BADDRESS VARCHAR(512),
BPHONE NUMERIC(10),
BFAX NUMERIC(10)
);""", """CREATE TABLE STORES_B(ISBN CHAR(10),
BINDEX INT,
BID CHAR(6),
PRIMARY KEY(ISBN, BINDEX),
FOREIGN KEY (BID) REFERENCES BRANCHES(BID),
FOREIGN KEY (ISBN) REFERENCES BOOKS(ISBN)
);""", """CREATE TABLE BOOKS(ISBN CHAR(10) PRIMARY KEY,
BTITLE VARCHAR(512),
BAUTHOR VARCHAR(64),
DDS CHAR(14),
BSUBJECT CHAR(32),
BGENRE CHAR(24),
BLANGUAGE VARCHAR(64),
BDESC VARCHAR(4096),
BPUB VARCHAR(64),
BYEAR DATE
);""", """CREATE TABLE PERIODICALS(PNAME VARCHAR(64),
PEDITION VARCHAR(64),
PGENRE CHAR(24),
PTYPE CHAR(16),
DDS CHAR(14),
PSUBJECT CHAR(32),
PRIMARY KEY(PNAME, PEDITION)
);""", """CREATE TABLE STORES_P(PNAME VARCHAR(64),
PEDITION VARCHAR(64),
BID CHAR(6),
FOREIGN KEY (PNAME, PEDITION) REFERENCES
PERIODICALS (PNAME, PEDITION),
FOREIGN KEY (BID) REFERENCES BRANCHES(BID),
PRIMARY KEY(PNAME, PEDITION, BID)
);""", """CREATE TABLE CUSTOMERS(UNAME VARCHAR(32) PRIMARY KEY,
CARD NUMERIC(12) UNIQUE NOT NULL,
EMAIL VARCHAR(256),
CADDRESS VARCHAR(512),
CDOB DATE,
CPHONE NUMERIC(10),
CSTANDING CHAR(7) CHECK(CSTANDING='GOOD' OR
CSTANDING='OVERDUE') DEFAULT 'GOOD',
CFINES NUMERIC(9, 2) CHECK(CFINES >= 0) DEFAULT 0
);""", """CREATE TABLE CHECKED_OUT(UNAME VARCHAR(32),
ISBN CHAR(10),
BINDEX INT,
RENEWALS INT DEFAULT 2,
DUE DATE NOT NULL,
PRIMARY KEY (ISBN, BINDEX),
FOREIGN KEY (ISBN, BINDEX) REFERENCES
STORES_B(ISBN, BINDEX),
FOREIGN KEY (UNAME) REFERENCES CUSTOMERS(UNAME)
);""")

for eachStr in tableStrs:
    dbCursor.execute(eachStr)
conn.commit()
